In [2]:
import torch
import torch.nn as nn
import torchvision
print(torch.__version__)
print(torch.version.cuda)
print(torch.backends.cudnn.version())
print(torch.cuda.get_device_name(0))

1.6.0
10.2
7605
NVIDIA GeForce GTX 1050 Ti


In [4]:
# 可复现性
import numpy as np
np.random.seed(0)
torch.manual_seed(0)
torch.cuda.manual_seed_all(0)

torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

In [5]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)

cuda


In [6]:
import os
os.environ['CUDA_VISBLE_DEVICES'] = '0,1' # 命令行指定gpu device: CUDA_VISBLE_DEVICES=0,1 python *.py

In [7]:
torch.cuda.empty_cache() # nvidia-smi --gpu-reset -i 0

In [13]:
# 张量处理
tensor = torch.randn(3,4,5)
print(tensor.type())
print(tensor.size())
print(tensor.dim())

torch.FloatTensor
torch.Size([3, 4, 5])
3


In [10]:
torch.set_default_tensor_type(torch.FloatTensor)
tensor = tensor.cuda()
tensor = tensor.cpu()
tensor = tensor.float()
tensor = tensor.long()

In [14]:
ndarray = tensor.cpu().numpy()
tensor = torch.from_numpy(ndarray)
print(tensor.type())
tensor = tensor.float()
tensor = torch.from_numpy(ndarray.copy()).float()

torch.FloatTensor


In [18]:
import PIL
image = PIL.Image.fromarray(torch.clamp(tensor*255, min=0, max=255).byte().permute(1,2,0).cpu().numpy())
image1 = torchvision.transforms.functional.to_pil_image(tensor) #与上面等价
print(image)

<PIL.Image.Image image mode=RGB size=5x4 at 0x297376A7148>


In [ ]:
tensor = torch.from_numpy(np.asarray(PIL.Image.open('fig.png')).permute(2,0,1).float()/255
tensor1 = torchvision.transforms.functional.to_tensor(PIL.Image.open('fig.png'))

In [34]:
print(ndarray.shape)
image = PIL.Image.fromarray(ndarray.astype(np.uint8).transpose(1,2,0))
print(image)
image1 = np.asarray(PIL.Image.open('fig.png'))

(3, 4, 5)
<PIL.Image.Image image mode=RGB size=5x4 at 0x297372544C8>


In [37]:
value =  torch.rand(1).item()
print(value)

0.7703205347061157


In [39]:
tensor = torch.rand(2,3,4)
tensor = torch.reshape(tensor, (6,4))
print(tensor.shape)

torch.Size([6, 4])


In [41]:
tensor = tensor[torch.randperm(tensor.size(0))]


In [50]:
tensor = torch.rand(2,3,4,5)
tensor = tensor[:,:,:,torch.arange(tensor.size(3)-1, -1,-1).long()]

In [51]:
tensor.clone()
tensor.detach()
tensor.detach().clone()

tensor([[[[0.0067, 0.1617, 0.6129, 0.1508, 0.7438],
          [0.9006, 0.9691, 0.7705, 0.8947, 0.0985],
          [0.8472, 0.1753, 0.4192, 0.1588, 0.0535],
          [0.9112, 0.2161, 0.0170, 0.2560, 0.1220]],

         [[0.3720, 0.9446, 0.8861, 0.8579, 0.9094],
          [0.7593, 0.9998, 0.6654, 0.9455, 0.7200],
          [0.3806, 0.5575, 0.7399, 0.3250, 0.8108],
          [0.8555, 0.8357, 0.1153, 0.2194, 0.2181]],

         [[0.5372, 0.8197, 0.8865, 0.2107, 0.4431],
          [0.9785, 0.1204, 0.7045, 0.9595, 0.2639],
          [0.4216, 0.2159, 0.7811, 0.3178, 0.8797],
          [0.3643, 0.3329, 0.1464, 0.5207, 0.9246]]],


        [[[0.1913, 0.5268, 0.9624, 0.5479, 0.4035],
          [0.4105, 0.0430, 0.7480, 0.7397, 0.5256],
          [0.6859, 0.1449, 0.6801, 0.2867, 0.1284],
          [0.6092, 0.3209, 0.1668, 0.5328, 0.9244]],

         [[0.0142, 0.0194, 0.0461, 0.7484, 0.1188],
          [0.3000, 0.9156, 0.0268, 0.8362, 0.3986],
          [0.7692, 0.9147, 0.0491, 0.5228, 0.6464],
  

In [52]:
tensor1 = torch.rand(2,3,4)
tensor2 = torch.rand(2,3,4)
tensor_cat = torch.cat([tensor1, tensor2],dim=0)
print(tensor_cat.shape)
tensor_stack = torch.stack([tensor1, tensor2], dim=0)
print(tensor_stack.shape)

torch.Size([4, 3, 4])
torch.Size([2, 2, 3, 4])


In [54]:
tensor = torch.tensor([0,2,1,3])
N = tensor.size(0)
print(N)
n_c = 4
one_hot = torch.zeros(N,4).long()
print(one_hot)
one_hot.scatter_(dim=1, index=torch.unsqueeze(tensor, dim=1), src=torch.ones(N, n_c).long())
print(one_hot)

4
tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])
tensor([[1, 0, 0, 0],
        [0, 0, 1, 0],
        [0, 1, 0, 0],
        [0, 0, 0, 1]])


In [57]:
index=torch.unsqueeze(tensor, dim=1)
print(index.shape)

torch.Size([4, 1])


In [ ]:
torch.nozero(tensor).size(0)
torch.nozero(tensor==0)

In [61]:
tensor=torch.tensor([0,1,2])
print(tensor==0)

tensor([ True, False, False])


In [63]:
torch.allclose(tensor1,tensor2)

False

In [64]:
tensor = torch.rand(64,512)
torch.reshape(tensor,(64,512,1,1)).expand(64,512,7,7)

tensor([[[[0.2462, 0.2462, 0.2462,  ..., 0.2462, 0.2462, 0.2462],
          [0.2462, 0.2462, 0.2462,  ..., 0.2462, 0.2462, 0.2462],
          [0.2462, 0.2462, 0.2462,  ..., 0.2462, 0.2462, 0.2462],
          ...,
          [0.2462, 0.2462, 0.2462,  ..., 0.2462, 0.2462, 0.2462],
          [0.2462, 0.2462, 0.2462,  ..., 0.2462, 0.2462, 0.2462],
          [0.2462, 0.2462, 0.2462,  ..., 0.2462, 0.2462, 0.2462]],

         [[0.9595, 0.9595, 0.9595,  ..., 0.9595, 0.9595, 0.9595],
          [0.9595, 0.9595, 0.9595,  ..., 0.9595, 0.9595, 0.9595],
          [0.9595, 0.9595, 0.9595,  ..., 0.9595, 0.9595, 0.9595],
          ...,
          [0.9595, 0.9595, 0.9595,  ..., 0.9595, 0.9595, 0.9595],
          [0.9595, 0.9595, 0.9595,  ..., 0.9595, 0.9595, 0.9595],
          [0.9595, 0.9595, 0.9595,  ..., 0.9595, 0.9595, 0.9595]],

         [[0.3655, 0.3655, 0.3655,  ..., 0.3655, 0.3655, 0.3655],
          [0.3655, 0.3655, 0.3655,  ..., 0.3655, 0.3655, 0.3655],
          [0.3655, 0.3655, 0.3655,  ..., 0

In [65]:
torch.mm
torch.bmm
tensor1*tensor2

tensor([[[0.6253, 0.1627, 0.5894, 0.1358],
         [0.0582, 0.0580, 0.5362, 0.1582],
         [0.5905, 0.2883, 0.6284, 0.1864]],

        [[0.1083, 0.2449, 0.3837, 0.1912],
         [0.0815, 0.7263, 0.2006, 0.0528],
         [0.0871, 0.6364, 0.1319, 0.0076]]])

In [ ]:
dist = torch.